chore: Remove duplicates when merging datapoints
I noticed during testing that it's possible to have duplicated datapoints
when merging them. This happens if you have multiple report files uploaded
in one go.

That is useless and just takes up space. So by removing these duplicates we
save space and increase performance, even if by a negligible amount.

Not using a set to remove duplicates because the datapoint isn't hasheable.
But it's string representation works for the purposes of spotting duplicates

```
>>> l1 = (0, 1, None, [])
>>> str(l1)
'(0, 1, None, [])'
>>> S = set()
>>> S.add(l1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'list'
```